title: "Ziyao Zhang (梓垚 张)"
author: "Ziyao Zhang (梓垚 张)"
description: "UT Austin"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", icon: dolphin,file: "home.html"}
  - {title: "CV", icon: adress-card,file:"ziyao.pdf"}
  - {title: "Papers", icon: print,file: "papers.html"}
  - {title: "Posters", icon: projector,file: "posters.html"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "ziyaopsy@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ZiyaoZZ"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ziyaozhangzz"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
